const {JSDOM}=require('jsdom'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../public');
function app(saved){const d=new JSDOM(fs.readFileSync(root+'/index.html','utf8'),{url:'https://test.local/',runScripts:'outside-only'}),w=d.window;w.structuredClone=structuredClone;w.alert=()=>{};w.confirm=()=>true;w.setTimeout=()=>0;w.setInterval=()=>0;w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.fetch=async()=>({ok:true,json:async()=>({build:'20260928-prod-01'})});if(saved)w.localStorage.setItem('my-asset-hub-beta-v4',JSON.stringify(saved));for(const f of ['vendor/xlsx.full.min.js','js/portfolio.js','js/cashflow.js','js/app.js'])w.eval(fs.readFileSync(root+'/'+f,'utf8'));return w}
const w=app(),P=w.Portfolio,base=w.AssetHub.getState(),clone=x=>JSON.parse(JSON.stringify(x));let passed=0;
const test=(name,fn)=>{fn();passed++;console.log('PASS',name)},stock=(id,q=0,p=100000)=>({id,name:id,ticker:id,buy:p,buyKrw:p,quantity:q,price:p,foreign:false,risk:'risk_2',market:'KRX'}),bank=(id,balance,liquidityType='liquid',displayOrder=0)=>({id,name:id,type:'파킹통장',amount:balance,balance,liquidityType,displayOrder,risk:'risk_4'});
function state(stocks=[stock('AAPL')],savings=[bank('fixed',3000000,'fixed'),bank('liquid',5000000)],cash=0){return w.AssetHub.normalize({...clone(base),stocks,savings,cash:{amount:cash},config:{...clone(base.config),minCash:2000000},riskTargets:{risk_1:0,risk_2:100,risk_3:0,risk_4:0},allocations:{...Object.fromEntries([...stocks.map(x=>[x.id,100/stocks.length]),...savings.map(x=>[x.id,0])]),cash:0}})}
const fills=p=>p.trades.filter(x=>x.delta).map(x=>({id:x.id,quantity:Math.abs(x.delta),price:x.price,fee:0}));
for(const mode of ['investment','rebalance'])test(mode+': fixed 3m excluded, liquid 5m included, reserve 2m, total conserved',()=>{const s=state(),p=P.plan(s,{mode,fromCash:true,contribution:5000000});assert.equal(P.liquidTotal(s),5000000);assert.equal(p.trades[0].amount,3000000);const n=P.execute(s,p,fills(p));assert.equal(n.savings[0].balance,3000000);assert.equal(n.savings[1].balance,2000000);assert.equal(P.calc(n).total,P.calc(s).total);assert(n.cash.amount>=0&&n.savings.every(x=>x.balance>=0));assert.equal(p.cashAfter,P.liquidTotal(n));for(const g of p.afterGroups){const pct=P.items(n).filter(x=>x.risk===g.id).reduce((sum,x)=>sum+x.value,0)/P.calc(n).total*100;assert(Math.abs(g.after-pct)<1e-8)}});
test('partial fills and fee debit cash first, then bank displayOrder with stable tie break',()=>{const s=state([stock('AAPL')],[bank('later',2000000,'liquid',2),bank('first',1000000,'liquid',1)],100000);s.config.minCash=200000;const p=P.plan(s,{mode:'investment',fromCash:true,contribution:800000}),n=P.execute(s,p,[{id:'AAPL',quantity:5,price:100000,fee:500}]);assert.equal(n.cash.amount,0);assert.equal(n.savings.find(x=>x.id==='first').balance,599500);assert.equal(n.savings.find(x=>x.id==='later').balance,2000000);assert.equal(P.calc(n).total,P.calc(s).total-500);assert.deepEqual(clone(n.transactions.at(-1).funding),[{id:'cash',amount:-100000},{id:'first',amount:-400500}]);assert.equal(n.cashflows.length,0)});
test('actual fee cannot invade aggregate reserve; state unchanged on rejected fill',()=>{const s=state(),before=clone(s),p=P.plan(s,{mode:'investment',fromCash:true,contribution:4000000}),f=fills(p);f[0].fee=1;assert.throws(()=>P.execute(s,p,f),/최소 현금/);assert.deepEqual(clone(s),before)});
test('monthly overweights never sell, excluded asset never buys, stock integer/coin fractional',()=>{const s=state([stock('AAPL',30),stock('QQQ'),stock('005930'),stock('KRW-BTC',0,70000000)],[],2000000);s.config.minCash=100000;s.allocations={AAPL:10,QQQ:30,'005930':30,'KRW-BTC':30,cash:0};const opt={mode:'investment',fromCash:true,contribution:2000000,excluded:['005930']},p=P.plan(s,opt);assert(p.trades.every(t=>t.delta>=0));assert.equal(p.trades.find(t=>t.id==='AAPL').delta,0);assert.equal(p.trades.find(t=>t.id==='005930').delta,0);assert(p.trades.filter(t=>!t.crypto).every(t=>Number.isInteger(t.delta)));const btc=p.trades.find(t=>t.crypto);assert(btc.delta>0&&btc.delta<1);assert(p.cashAfter>=100000);assert(p.trades.reduce((sum,t)=>sum+t.amount,0)<=1900000);assert.deepEqual(clone(p.trades),clone(P.plan(s,opt).trades))});
test('locked QQQ 5 shares unchanged after full execution with liquid bank funding',()=>{const s=state([stock('QQQ',5),stock('AAPL')]);s.allocations={QQQ:0,AAPL:100,fixed:0,liquid:0,cash:0};const p=P.plan(s,{lockedIds:['QQQ']}),n=P.execute(s,p,fills(p));assert.equal(n.stocks[0].quantity,5);assert.equal(n.savings[0].balance,3000000);assert(p.warnings.some(x=>x.includes('최소 가능 비중')))});
test('bank funding execution undo restores every balance and transaction',()=>{const s=state(),v=app(s),q=id=>v.document.querySelector(id);q('#calculate-plan').click();q('#start-fills').click();q('#fills-form').dispatchEvent(new v.Event('submit',{cancelable:true}));assert.equal(v.AssetHub.getState().savings[1].balance,2000000);q('#undo-rebalance').click();assert.deepEqual(clone(v.AssetHub.getState().savings),clone(s.savings));assert.equal(v.AssetHub.getState().transactions.length,0);v.close()});
test('full STEP 3 contains no legacy monthly controls',()=>{for(const id of ['plan-mode','contribution','investment-method','investment-exclusions','investment-options'])assert.equal(w.document.getElementById(id),null);assert(w.document.querySelector('#monthly-view #monthly-exclusions'));assert(w.document.querySelector('#step3 #calculate-plan'))});
test('fixed asset percentage changes with external salary while balance remains constant',()=>{const s=state();s.config.salary={amount:4500000,day:1,targetId:'cash',autoApply:true};const n=w.Cashflow.apply(s,Date.parse('2026-09-27T12:00:00Z')).state;assert.equal(n.savings[0].balance,s.savings[0].balance);assert.equal(P.calc(n).total-P.calc(s).total,4500000);assert(P.calc(n).banks[0].value/P.calc(n).total<P.calc(s).banks[0].value/P.calc(s).total)});
test('Excel imported into fresh app preserves custom risk IDs, ordering and target edits',()=>{let s=state();s.config.riskGroups[1].id='risk_custom';s.config.riskGroups[1].label='내 투자';s.config.risks[1]='risk_custom';s.stocks[0].risk='risk_custom';s.stocks[0].displayOrder=9;s.riskTargets={risk_custom:100};const source=app(s);let wb;source.XLSX.writeFile=x=>wb=x;source.document.querySelector('#excel-export-btn').click();wb.Sheets['설정'].B2.v=123456789;const out=w.AssetHub.readWorkbook(wb);assert.equal(out.stocks[0].risk,'risk_custom');assert.equal(out.stocks[0].displayOrder,9);assert.equal(out.config.target,123456789);source.close()});
test('v0.7 Excel installment value migration preserves balance',()=>{let s=state();s.version=3;s.savings=[{id:'old',name:'적금',type:'적금',amount:500000,current:7,total:12,rate:2,risk:'risk_4'}];const source=app(s);let wb;source.XLSX.writeFile=x=>wb=x;source.document.querySelector('#excel-export-btn').click();delete wb.Sheets['v08백업'];wb.Sheets['v07백업']=source.XLSX.utils.aoa_to_sheet([['순서','백업'],[0,JSON.stringify(s)]]);wb.Sheets['은행자산']=source.XLSX.utils.aoa_to_sheet([['ID','종류','상품명','금액','현재회차','총회차','이율'],['old','적금','적금',500000,7,12,2]]);assert.equal(w.AssetHub.readWorkbook(wb).savings[0].balance,3500000);source.close()});
test('fractional KRW weighted average editor rounds display without multiplying or losing basis',()=>{const s=state();s.stocks[0].buyKrw=500000/3;s.stocks[0].quantity=3;const v=app(s);v.document.querySelector('[data-edit="stock"]').click();const f=v.document.querySelector('#editor-form');assert.equal(f.elements.buy.value,'166,667');f.dispatchEvent(new v.Event('submit',{cancelable:true}));assert.equal(v.AssetHub.getState().stocks[0].buyKrw,500000/3);v.close()});
test('Worker name matches release channel',()=>{const cfg=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../wrangler.jsonc'),'utf8')),pkg=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../package.json'),'utf8'));if(pkg.version.includes('beta')){assert.equal(cfg.name,'my-asset-hub-v08-test');assert.notEqual(cfg.name,'my-asset-hub')}else assert.equal(cfg.name,'my-asset-hub')});
console.log(passed+' beta.2 independent tests PASS');w.close();
