const {chromium}=require('playwright');
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../public');
const groups=[1,2,3,4].map(i=>({id:'risk_'+i,label:['초고위험','위험','중립','안전'][i-1]}));
const stock=(id,ticker,market,foreign=false)=>({id,name:id,ticker,market,foreign,risk:'risk_2',buy:foreign?1:100,buyKrw:100,buyFx:100,quantity:1,price:foreign?1:100,displayOrder:['삼성전자','AAPL','QQQ','BTC'].indexOf(id)});
const fixture={version:4,config:{riskGroups:groups,risks:groups.map(g=>g.id),cashRiskId:'risk_4',target:100000,fx:100,refreshMinutes:0,minCash:0},stocks:[stock('삼성전자','005930','KRX'),stock('AAPL','AAPL','NASDAQ',true),stock('QQQ','QQQ','NASDAQ',true),stock('BTC','KRW-BTC','CRYPTO')],savings:[{id:'bank',name:'은행',type:'입출금통장',amount:1000,balance:1000,risk:'risk_4',displayOrder:0},{id:'bank2',name:'은행2',type:'파킹통장',amount:1000,balance:1000,risk:'risk_4',displayOrder:1}],cash:{amount:1000,displayOrder:2},riskTargets:{risk_1:0,risk_2:60,risk_3:20,risk_4:20},allocations:{삼성전자:15,AAPL:15,QQQ:15,BTC:15,bank:10,bank2:5,cash:5},history:[]};
(async()=>{
 let browser;const server=http.createServer((req,res)=>{const file=path.join(root,new URL(req.url,'http://localhost').pathname.replace(/^\//,'')||'index.html');if(!fs.existsSync(file)){res.writeHead(404);return res.end()}res.setHeader('content-type',file.endsWith('.js')?'application/javascript':file.endsWith('.png')?'image/png':file.endsWith('.webmanifest')?'application/manifest+json':'text/html');res.end(fs.readFileSync(file))});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));let passed=0;
 try{
 browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE||chromium.executablePath(),args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--no-zygote','--single-process','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-software-rasterizer']});
 const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true,serviceWorkers:'block'}),cdp=await page.context().newCDPSession(page),errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.route('**/api/**',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({version:require('../package.json').version,build:'20260928-beta-02'})}));
 await page.addInitScript(f=>{Object.defineProperty(navigator,'onLine',{get:()=>false});if(!sessionStorage.getItem('seeded')){localStorage.setItem('my-asset-hub-beta-v4',JSON.stringify(f));sessionStorage.setItem('seeded','1')}},fixture);
 await page.goto('http://127.0.0.1:'+server.address().port+'/');await page.waitForFunction(()=>window.AssetHub);
 const state=()=>page.evaluate(()=>AssetHub.getState());
 const test=async(name,fn)=>{await fn();passed++;console.log('PASS',name)};
 const openAssets=async()=>page.locator('[data-tab=assets]').click();
 // Trusted touch events and real browser hit-testing; no elementFromPoint replacement.
 async function drag(id,target){await openAssets();const handle=page.locator(`[data-drag-id="${id}"]`);await handle.scrollIntoViewIfNeeded();const a=await handle.boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:a.x+a.width/2,y:a.y+a.height/2}]});const dest=page.locator(target);await dest.evaluate(el=>el.scrollIntoView({block:'center'}));const b=await dest.boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:b.x+Math.min(b.width/2,100),y:b.y+Math.min(b.height/2,20)}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}
 await test('stock same-group reorder retains allocations and survives reload',async()=>{const before=await state();await drag('삼성전자','[data-drag-id="QQQ"]');let after=await state();assert.equal(after.stocks.find(x=>x.id==='AAPL').displayOrder,0);assert.equal(after.stocks.find(x=>x.id==='삼성전자').displayOrder,1);assert.deepEqual(after.allocations,before.allocations);await page.reload();await page.waitForFunction(()=>window.AssetHub);assert.equal((await state()).stocks.find(x=>x.id==='삼성전자').displayOrder,1)});
 for(const id of ['삼성전자','AAPL','QQQ','BTC','bank','cash'])await test(id+' cross-risk cancel/apply/reload; dashboard and plans reflect stable ID',async()=>{
  const before=await state();await drag(id,'#stock-list .asset-group[data-group="risk_3"] > h3');assert(await page.locator('#risk-drag-confirm').evaluate(el=>el.open));await page.locator('#risk-drag-cancel').click();assert.deepEqual(await state(),before);
  await drag(id,'#stock-list .asset-group[data-group="risk_3"] > h3');await page.locator('#risk-drag-apply').click();const after=await state(),find=s=>id==='cash'?s.config.cashRiskId:[...s.stocks,...s.savings].find(x=>x.id===id).risk;assert.equal(find(after),'risk_3');
  const check=await page.evaluate(id=>{const s=AssetHub.getState(),P=Portfolio,items=P.items(s),m=items.find(x=>x.id===id);const expected=items.filter(x=>x.risk==='risk_3').reduce((a,x)=>a+x.value,0)/P.calc(s).total*100;const v=P.validateTargets(s);return {risk:m.risk,display:document.querySelector('#risk-viz').textContent,expected:expected.toFixed(1)+'%',valid:v.step2,monthly:P.plan(s,{mode:'investment',contribution:100,fromCash:true}).trades.find(x=>x.id===id)?.risk,full:v.step2?P.plan(s).trades.find(x=>x.id===id)?.risk:null}},id);
  assert.equal(check.risk,'risk_3');assert(check.display.includes(check.expected));if(after.stocks.some(x=>x.id===id)){assert.equal(check.monthly,'risk_3');if(check.valid)assert.equal(check.full,'risk_3')}
  await page.reload();await page.waitForFunction(()=>window.AssetHub);assert.equal(find(await state()),'risk_3');
 });
 await test('cash and bank same-group reordering persists without target changes',async()=>{const before=await state();await drag('cash','[data-drag-id="bank"]');const after=await state();assert(after.cash.displayOrder<after.savings.find(x=>x.id==='bank').displayOrder);assert.deepEqual(after.allocations,before.allocations);await page.reload();await page.waitForFunction(()=>window.AssetHub);assert.equal((await state()).cash.displayOrder,after.cash.displayOrder)});
 await test('full quantity lock, partial actual fill/fee/undo and monthly liquid funding on mobile',async()=>{
  const f=structuredClone(fixture);f.stocks=[{...f.stocks[2],id:'QQQ',name:'QQQ',quantity:5,price:1000,buyKrw:100000},{...f.stocks[1],quantity:0,price:1000,buyKrw:100000}];f.cash.amount=1000000;f.savings=[{...f.savings[0],balance:3000000,amount:3000000,liquidityType:'liquid'},{...f.savings[1],balance:2000000,amount:2000000,liquidityType:'fixed'}];f.config.minCash=500000;f.riskTargets={risk_1:0,risk_2:60,risk_3:0,risk_4:40};f.allocations={QQQ:500000/6500000*100,AAPL:60-500000/6500000*100,bank:40-2000000/6500000*100,bank2:2000000/6500000*100,cash:0};
  await page.evaluate(f=>localStorage.setItem(AssetHub.storageKey,JSON.stringify(f)),f);await page.reload();await page.waitForFunction(()=>window.AssetHub);
  await page.locator('[data-tab=rebalance]').click();await page.locator('#full-tab').click();assert.equal(await page.locator('#step3 #plan-mode').count(),0);
  await page.locator('[data-lock="QQQ"]').check();assert((await page.locator('[data-allocation="QQQ"]').boundingBox()).width>=80);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await page.locator('[data-allocation="QQQ"]').isDisabled());await page.locator('#calculate-plan').click();assert(await page.locator('#plan-output details').evaluate(el=>!el.open));assert(!await page.locator('#plan-output').textContent().then(t=>t.includes('매수</')));await page.locator('#plan-output #start-fills').click();assert.equal(await page.locator('[data-fill-id="QQQ"]').count(),0);await page.locator('[data-fill-id="AAPL"] [data-fill-qty]').fill('3');await page.locator('[data-fill-fee]').fill('500');await page.locator('#fills-form [type=submit]').click();assert.equal((await state()).stocks.find(x=>x.id==='QQQ').quantity,5);assert.equal((await state()).cash.amount,699500);await page.locator('#undo-rebalance').click();assert.equal((await state()).cash.amount,1000000);
  await page.locator('#monthly-tab').click();await page.locator('#monthly-amount').fill('2000000');assert.equal(await page.locator('#monthly-amount').inputValue(),'2,000,000');await page.locator('#monthly-calculate').click();await page.locator('#monthly-plan #start-fills').click();assert.equal(await page.locator('[data-fill-id="QQQ"]').count(),0);await page.locator('#fills-form [type=submit]').click();assert.equal((await state()).cash.amount,0);assert.equal((await state()).savings[0].balance,2000000);assert.equal((await state()).savings[1].balance,2000000);await page.locator('#undo-investment').click();assert.equal((await state()).cash.amount,1000000);assert.equal((await state()).savings[0].balance,3000000);
 });
 await test('settings income, saving transfer popup, automatic undo, monthly idempotency on mobile',async()=>{
  await page.locator('#settings-btn').click();await page.locator('[name="salaryAmount"]').fill('4500000');assert.equal(await page.locator('[name="salaryAmount"]').inputValue(),'4,500,000');await page.locator('[name="salaryDay"]').fill('1');await page.locator('[name="salaryAutoApply"]').selectOption('true');await page.locator('[name="salaryTargetId"]').selectOption('cash');await page.locator('#settings-form [type=submit]').click();
  await openAssets();await page.locator('[data-edit="bank"][data-id="bank"]').click();await page.locator('#editor [name="type"]').selectOption('적금');await page.locator('#editor [name="liquidityType"]').selectOption('fixed');await page.locator('#editor [name="monthlyPayment"]').fill('500000');await page.locator('#editor [name="paymentDay"]').fill('1');await page.locator('#editor [name="sourceAssetId"]').selectOption('cash');await page.locator('#editor [name="autoApply"]').selectOption('true');await page.locator('#editor-form [type=submit]').click();
  const before=await state();await page.reload();await page.waitForFunction(()=>window.AssetHub);assert(await page.locator('#recurring-summary').evaluate(x=>x.open));assert.equal((await state()).cash.amount,5000000);assert.equal((await state()).savings[0].balance,3500000);assert((await page.locator('#recurring-net').textContent()).includes('4,500,000'));await page.locator('#recurring-undo').click();assert.equal((await state()).cash.amount,before.cash.amount);assert.equal((await state()).savings[0].balance,before.savings[0].balance);
  await page.reload();await page.waitForFunction(()=>window.AssetHub);await page.locator('#recurring-close').click();const applied=await state();await page.reload();await page.waitForFunction(()=>window.AssetHub);assert(!await page.locator('#recurring-summary').evaluate(x=>x.open));assert.equal((await state()).cash.amount,applied.cash.amount);assert.equal((await state()).transactions.length,applied.transactions.length);
 });
 await test('JSON file export/import restores holdings, stable risks, recurring ledger and history',async()=>{const before=await state();await page.locator('#backup-btn').click();const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#export-btn').click()]);const text=fs.readFileSync(await download.path(),'utf8'),raw=JSON.parse(text);assert.deepEqual(raw.stocks,before.stocks);assert.deepEqual(raw.recurringApplied,before.recurringApplied);await page.locator('#import-file').setInputFiles({name:'test-backup.json',mimeType:'application/json',buffer:Buffer.from(text)});await page.locator('#apply-import').click();await page.reload();await page.waitForFunction(()=>window.AssetHub);const after=await state();for(const k of ['stocks','savings','cash','config','riskTargets','allocations','transactions','recurringApplied'])assert.deepEqual(after[k],before[k])});
 await test('cash editor uses live comma formatting and numeric persistence',async()=>{await openAssets();await page.locator('[data-edit="cash"]').click();await page.locator('#editor [name="balance"]').fill('1000000');assert.equal(await page.locator('#editor [name="balance"]').inputValue(),'1,000,000');await page.locator('#editor-form [type=submit]').click();assert.equal((await state()).cash.amount,1000000);await page.reload();await page.waitForFunction(()=>window.AssetHub);assert.equal((await state()).cash.amount,1000000)});
 await test('no mobile horizontal overflow or JS errors',async()=>{assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[])});
 console.log(`${passed} independent mobile tests PASS`);
 }finally{await browser?.close();server.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
