const {JSDOM}=require('jsdom'),fs=require('fs'),path=require('path'),assert=require('assert');const root=path.resolve(__dirname,'../public'),KEY='my-asset-hub-beta-v4';
function app(saved,key=KEY){const d=new JSDOM(fs.readFileSync(root+'/index.html','utf8'),{url:'https://beta.test',runScripts:'outside-only'}),w=d.window;w.structuredClone=structuredClone;w.alert=()=>{};w.confirm=()=>true;w.prompt=()=>null;w.setTimeout=()=>0;w.setInterval=()=>0;w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.fetch=async url=>({ok:true,json:async()=>url.includes('/quote')?{price:120,currency:url.includes('USD')?'USD':'KRW',source:'fixture',asOf:'2026-09-26T00:00:00Z'}:url.includes('/fx')?{rate:1400,source:'fixture',asOf:'2026-09-26T00:00:00Z'}:{build:'20260926-beta-02'}});if(saved!=null)w.localStorage.setItem(key,typeof saved==='string'?saved:JSON.stringify(saved));for(const f of ['vendor/xlsx.full.min.js','js/portfolio.js','js/cashflow.js','js/app.js'])w.eval(fs.readFileSync(root+'/'+f,'utf8'));return {w,close:()=>d.window.close()}}
const a=app(),w=a.w,P=w.Portfolio,base=w.AssetHub.getState();let passed=0;const same=x=>JSON.parse(JSON.stringify(x));function test(name,fn){fn();passed++;console.log('PASS',name)}
function stock(id,quantity=0,price=100){return {id,name:id,ticker:id,buy:price,buyKrw:price,quantity,price,foreign:false,risk:'risk_2',market:'KRX',buyFx:null,quoteAsOf:'2026-09-26T00:00:00Z',quoteSource:'fixture',quoteError:''}}
function state(stocks=[stock('A')],cash=2000){return w.AssetHub.normalize({...same(base),stocks,cash:{amount:cash},riskTargets:{risk_1:0,risk_2:100,risk_3:0,risk_4:0},allocations:{...Object.fromEntries(stocks.map(x=>[x.id,100/stocks.length])),cash:0}})}
function fills(p){return p.trades.filter(t=>t.delta).map(t=>({id:t.id,quantity:Math.abs(t.delta),price:t.price,fee:0}))}
test('A: 90% locks plan',()=>{const s=state();s.riskTargets.risk_2=90;assert.equal(P.validateTargets(s).step1,false);assert.throws(()=>P.plan(s))});
test('B: 100% unlocks',()=>assert.equal(P.validateTargets(state()).step2,true));
for(const n of [2,3])test(n===2?'C: 30% split 15/15':'D: 30% split 10/10/10',()=>{let s=state(Array.from({length:n},(_,i)=>stock('S'+i)));s.riskTargets.risk_2=30;s.riskTargets.risk_4=70;s=P.distribute(s);for(const x of s.stocks)assert.equal(s.allocations[x.id],30/n)});
test('E: edited allocation retained by missing-only initialization',()=>{let s=state([stock('A'),stock('B')]);s.allocations={A:12,B:88,cash:0};s=P.distribute(s,'equal',true);assert.equal(s.allocations.A,12)});
test('F: 13.6 rounds to 14 with adequate cash',()=>{const s=state([stock('A',0,100)],2000);s.riskTargets={risk_2:68,risk_4:32};s.allocations={A:68,cash:32};assert.equal(P.plan(s).trades[0].target,14)});
test('G: rounded budget overflow adjusted',()=>{const s=state([stock('A',0,100),stock('B',0,100)],300);const p=P.plan(s);assert(p.cashAfter>=0);assert.equal(p.trades.reduce((a,t)=>a+t.target,0),3)});
test('H: crypto fractional quantity',()=>{const s=state([stock('KRW-BTC',0,100000)],1000);const p=P.plan(s);assert.equal(p.trades[0].target,.01)});
test('I/J: cash remainder and holdings after rebalance',()=>{const s=state([stock('A',0,300)],1000),p=P.plan(s),n=P.execute(s,p,fills(p));assert.equal(n.stocks[0].quantity,3);assert.equal(n.cash.amount,100);assert.equal(P.calc(n).total,1000)});
test('L: monthly 2m buy only',()=>{const s=state([stock('A',5,100000)],0),p=P.plan(s,{mode:'investment',contribution:2000000});assert(p.trades.every(t=>t.delta>=0));assert(p.trades.reduce((a,t)=>a+t.amount,0)<=2000000)});
test('M: min cash 300k caps 2m investment at 1.7m',()=>{const s=state([stock('A',0,10000)],0);s.config.minCash=300000;const p=P.plan(s,{mode:'investment',contribution:2000000});assert.equal(p.cashAfter,300000);assert.equal(p.trades[0].amount,1700000)});
test('N/O/P: partial fill 5->3, KRW weighted basis, history/contribution',()=>{const s=state([stock('A',2,100)],0);s.stocks[0].buyKrw=80;const p=P.plan(s,{mode:'investment',contribution:500}),n=P.execute(s,p,[{id:'A',quantity:3,price:110,fee:10}]);assert.equal(n.stocks[0].quantity,5);assert.equal(n.stocks[0].buyKrw,100);assert.equal(n.cash.amount,160);assert.equal(n.transactions.length,1);assert.equal(n.cashflows[0].amount,500)});
test('Q: cash label rename preserves IDs and math',()=>{const s=state(),g=same(s.config.riskGroups);g[3].label='현금성 자산';const n=P.renameRisks(s,g,'risk_4');assert.equal(P.calc(s).total,P.calc(n).total);assert.equal(n.config.cashRiskId,'risk_4');assert.equal(n.config.riskGroups[3].label,'현금성 자산')});
test('risk deletion moves stocks and targets',()=>{const s=state(),groups=s.config.riskGroups.filter(g=>g.id!=='risk_2');const n=P.renameRisks(s,groups,'risk_4',{risk_2:'risk_3'});assert.equal(n.stocks[0].risk,'risk_3');assert.equal(n.riskTargets.risk_3,100)});
test('T: legacy storage copied, original and migration backup intact',()=>{const raw=JSON.stringify({version:2,config:{fx:1300,risks:['초고위험','위험','중립','안전']},stocks:[{id:'old',name:'Apple',ticker:'AAPL',foreign:true,buy:100,buyFx:1200,quantity:10,price:110,risk:'위험'}],savings:[],history:[{date:'2026-09-01',total:1}]});const b=app(raw,'my-asset-hub-html-v1');assert.equal(b.w.localStorage.getItem('my-asset-hub-html-v1'),raw);assert.equal(b.w.localStorage.getItem(KEY+'-before-migration'),raw);assert.equal(b.w.AssetHub.getState().stocks[0].buyKrw,120000);assert.equal(b.w.AssetHub.getState().stocks[0].buyFx,1200);b.close()});
test('corrupt and future schema never overwrite raw',()=>{for(const raw of ['{broken',JSON.stringify({version:99})]){const b=app(raw);assert.equal(b.w.localStorage.getItem(KEY),raw);b.close()}});
test('fixed bank untouched and impossible warning',()=>{const s=state();s.savings=[{id:'bank',name:'청약',type:'주택청약',amount:1000000,current:10,total:12,rate:2,risk:'risk_4'}];s.allocations.bank=0;const normalized=w.AssetHub.normalize(s),p=P.plan(normalized);assert(p.warnings.some(x=>x.includes('최소 가능 비중')));const n=P.execute(normalized,p,fills(p));assert.deepEqual(same(n.savings),same(normalized.savings))});
test('regular mode shares targets, exclusion, cash reserve percent',()=>{const s=state([stock('A',0,100),stock('B',0,100)],0);s.config.minCashMode='percent';s.config.minCash=10;let p=P.plan(s,{mode:'investment',method:'regular',contribution:1000,excluded:['A']});assert.equal(p.trades[0].delta,0);assert(p.cashAfter>=100);assert(p.trades[1].delta>0)});
test('overspend actual price, stale plan, oversell rejected',()=>{const s=state(),p=P.plan(s);assert.throws(()=>P.execute(s,p,[{id:'A',quantity:p.trades[0].target,price:999999}]));s.cash.amount++;assert.throws(()=>P.execute(s,p,fills(p)))});
test('sell then buy, sell basis retained, fee deducted',()=>{const s=state([stock('A',10,100),stock('B',0,100)],0);s.stocks[0].buyKrw=70;s.allocations={A:0,B:100,cash:0};const p=P.plan(s),ff=fills(p);ff.find(x=>x.id==='B').quantity=9;ff.find(x=>x.id==='A').fee=10;const n=P.execute(s,p,ff);assert.equal(n.stocks[0].buyKrw,70);assert.equal(n.cash.amount,90);assert.equal(n.stocks[1].quantity,9)});
test('foreign cost stays KRW when FX changes',()=>{const s=state();s.stocks[0].foreign=true;s.stocks[0].buyKrw=278000;s.stocks[0].quantity=10;const cost=P.calc(s).cost;s.config.fx=1700;assert.equal(P.calc(s).cost,cost)});
test('legacy Excel without v3 sheets keeps existing cash and histories',()=>{const original=state();original.cash.amount=12345;original.transactions=[{id:'prior',trades:[],at:'2026-09-01',type:'investment'}];const b=app(original),v=b.w,wb=v.XLSX.utils.book_new();for(const[name,rows]of Object.entries({stocks:[{'종목명':'삼성전자','티커':5930,'매수평단가':100,'보유수량':2,'해외여부':'FALSE','리스크':'위험 (ETF&빅테크)'}],savings:[],config:[]}))v.XLSX.utils.book_append_sheet(wb,v.XLSX.utils.json_to_sheet(rows),name);const n=v.AssetHub.readWorkbook(wb);assert.equal(n.cash.amount,12345);assert.equal(n.transactions[0].id,'prior');assert.equal(n.stocks[0].ticker,'005930');b.close()});
test('sell fee cannot cause negative cash',()=>{const s=state([stock('A',1,100)],0);s.riskTargets={risk_4:100};s.allocations={A:0,cash:100};const p=P.plan(s);assert.throws(()=>P.execute(s,p,[{id:'A',quantity:1,price:100,fee:200}]))});
test('save failure rolls back actual portfolio and protects persisted state',()=>{const b=app(state([stock('A',0,300)],1000)),v=b.w,$=q=>v.document.querySelector(q);$('#calculate-plan').click();$('#start-fills').click();const raw=v.localStorage.getItem(KEY),native=v.Storage.prototype.setItem;v.Storage.prototype.setItem=function(k,value){if(k===KEY)throw Error('quota exceeded');return native.call(this,k,value)};$('#fills-form').dispatchEvent(new v.Event('submit',{cancelable:true}));assert.equal(v.localStorage.getItem(KEY),raw);assert.equal(v.AssetHub.getState().stocks[0].quantity,0);b.close()});
// In-app execution UI and undo, using a new persisted test instance.
test('K/J: confirmation cancellation, actual apply, snapshot undo',()=>{const b=app(state([stock('A',0,300)],1000)),v=b.w,$=q=>v.document.querySelector(q);$('#calculate-plan').click();$('#start-fills').click();v.confirm=()=>false;$('#fills-form').dispatchEvent(new v.Event('submit',{cancelable:true}));assert.equal(v.AssetHub.getState().stocks[0].quantity,0);v.confirm=()=>true;$('#fills-form').dispatchEvent(new v.Event('submit',{cancelable:true}));assert.equal(v.AssetHub.getState().stocks[0].quantity,3);assert(v.localStorage.getItem(KEY+'-before-rebalance'));$('#undo-rebalance').click();assert.equal(v.AssetHub.getState().stocks[0].quantity,0);assert.equal(v.AssetHub.getState().cash.amount,1000);b.close()});
test('DOM actual stage disabled state',()=>{const s=state();s.riskTargets.risk_2=90;const b=app(s);assert.equal(b.w.document.querySelector('#step2').disabled,true);assert.equal(b.w.document.querySelector('#step3').disabled,true);b.close()});
test('Excel full new schema binary roundtrip',()=>{const b=app(state()),v=b.w;let wb;v.XLSX.writeFile=x=>wb=x;v.document.querySelector('#excel-export-btn').click();assert(wb.Sheets['v08백업']);const out=v.AssetHub.readWorkbook(v.XLSX.read(v.XLSX.write(wb,{type:'array',bookType:'xlsx'}),{type:'array'}));const old=v.AssetHub.getState();for(const k of ['stocks','savings','cash','config','riskTargets','allocations','transactions','cashflows','history'])assert.deepEqual(same(out[k]),same(old[k]),k);b.close()});
(async()=>{for(const foreign of [false,true]){const b=app(),v=b.w;v.document.querySelector('#add-stock').click();await v.AssetHub.applyEditorMarketSelection({name:foreign?'Apple':'삼성전자',ticker:foreign?'AAPL':'005930',market:foreign?'NASDAQ':'KOSPI',currency:foreign?'USD':'KRW'});test(foreign?'S: AAPL auto fields/price':'R: Samsung auto fields/price',()=>{const f=v.document.querySelector('#editor-form');assert.equal(f.elements.ticker.value,foreign?'AAPL':'005930');assert.equal(f.elements.foreign.value,String(foreign));assert.equal(Number(f.elements.price.value),120)});b.close()}console.log(`${passed} v0.7 tests PASS`);a.close()})().catch(e=>{console.error(e);process.exit(1)});
