const {JSDOM}=require('jsdom'),fs=require('fs'),path=require('path'),assert=require('assert');const root=path.resolve(__dirname,'../public'),KEY='my-asset-hub-beta-v4',OLD='my-asset-hub-beta-v3';let pass=0;
function setup(raw,key=OLD){const d=new JSDOM(fs.readFileSync(root+'/index.html','utf8'),{url:'https://test.local/',runScripts:'outside-only'}),w=d.window;w.structuredClone=structuredClone;w.alert=()=>{};w.confirm=()=>true;w.prompt=()=>null;w.setTimeout=()=>0;w.setInterval=()=>0;w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.fetch=async()=>({ok:true,json:async()=>({build:'20260927-beta-01'})});if(raw)w.localStorage.setItem(key,typeof raw==='string'?raw:JSON.stringify(raw));for(const f of ['vendor/xlsx.full.min.js','js/portfolio.js','js/cashflow.js','js/app.js'])w.eval(fs.readFileSync(root+'/'+f,'utf8'));return {w,close:()=>d.window.close()}}
function t(name,fn){fn();pass++;console.log('PASS',name)}const b=setup(),w=b.w,defaultState=w.AssetHub.getState();function fresh(extra={}){return w.AssetHub.normalize({...structuredClone(defaultState),...extra})}const stock=(id,qty=0,price=100,risk='risk_2',ticker=id)=>({id,name:id,ticker,buy:price,buyKrw:price,quantity:qty,price,foreign:false,risk,market:'KRX'});
t('v0.7 savings migration retains old valuation and original key',()=>{let raw={...defaultState,version:3,savings:[{id:'bank',name:'청약',type:'주택청약',amount:500000,current:7,total:12,rate:2,risk:'risk_4'}]};const x=setup(raw);const n=x.w.AssetHub.getState();assert.equal(n.savings[0].balance,3500000);assert.equal(n.savings[0].monthlyPayment,500000);assert.equal(n.savings[0].liquidityType,'fixed');assert.equal(x.w.localStorage.getItem(OLD),JSON.stringify(raw));assert(x.w.localStorage.getItem(KEY+'-before-migration'));x.close()});
t('money formatter caret and internal value',()=>{const x=setup(),el=x.w.document.querySelector('#monthly-amount');el.value='1000000';el.setSelectionRange(7,7);el.dispatchEvent(new x.w.Event('input',{bubbles:true}));assert.equal(el.value,'1,000,000');assert.equal(x.w.AssetHub.normalize({...x.w.AssetHub.getState(),config:{...x.w.AssetHub.getState().config,monthlyInvestment:Number(el.value.replaceAll(',',''))}}).config.monthlyInvestment,1000000);x.close()});
t('liquidity defaults and explicit override',()=>{const s=fresh({savings:[{id:'s',name:'적금',type:'적금',amount:1,current:1,total:1},{id:'a',name:'입출금',type:'입출금통장',amount:2,current:1,total:1}]});assert.equal(s.savings[0].liquidityType,'fixed');assert.equal(s.savings[1].liquidityType,'liquid');s.savings[0].liquidityType='liquid';assert.equal(w.AssetHub.normalize(s).savings[0].liquidityType,'liquid')});
t('salary one per KST month, external asset increase',()=>{let s=fresh();s.config.salary={amount:4500000,day:1,autoApply:true,targetId:'cash'};const now=Date.parse('2026-09-10T01:00:00Z'),first=w.Cashflow.apply(s,now),again=w.Cashflow.apply(first.state,now);assert.equal(first.state.cash.amount,4500000);assert.equal(first.net,4500000);assert.equal(first.changes[0].id,'salary:2026-09');assert.equal(again.changes.length,0);assert.equal(again.state.cash.amount,4500000)});
t('savings transfer preserves total, and pending on insufficient cash',()=>{let s=fresh({cash:{amount:2000000},savings:[{id:'s',name:'적금',type:'적금',amount:3000000,balance:3000000,current:1,total:1,monthlyPayment:500000,paymentDay:1,autoApply:true,sourceAssetId:'cash',risk:'risk_4'}]});const before=w.Portfolio.calc(s).total,done=w.Cashflow.apply(s,Date.parse('2026-09-10T01:00:00Z'));assert.equal(done.state.cash.amount,1500000);assert.equal(done.state.savings[0].balance,3500000);assert.equal(w.Portfolio.calc(done.state).total,before);assert.equal(done.net,0);s.cash.amount=0;assert.equal(w.Cashflow.apply(s,Date.parse('2026-09-10T01:00:00Z')).pending.length,1)});
t('popup and undo of applied salary',()=>{let s=fresh();s.config.salary={amount:4500000,day:1,autoApply:true,targetId:'cash'};const x=setup(s,KEY),v=x.w;assert(v.document.querySelector('#recurring-summary').open);assert.equal(v.AssetHub.getState().cash.amount,4500000);v.document.querySelector('#recurring-undo').click();assert.equal(v.AssetHub.getState().cash.amount,0);assert.equal(v.AssetHub.getState().transactions.length,0);x.close()});
t('no popup without changes',()=>{const x=setup();assert(!x.w.document.querySelector('#recurring-summary').open);x.close()});
t('monthly investment uses existing cash, no sells/overspend, integer stock and fractional crypto',()=>{const s=fresh({stocks:[stock('A',1,100),stock('B',0,100),stock('C',0,100000,'risk_2','KRW-BTC')],cash:{amount:1000},riskTargets:{risk_1:0,risk_2:100,risk_3:0,risk_4:0},allocations:{A:10,B:40,C:50,cash:0}});const p=w.Portfolio.plan(s,{mode:'investment',fromCash:true,contribution:900});assert(p.trades.every(x=>x.delta>=0));assert(p.trades.every(x=>x.crypto||Number.isInteger(x.target)));assert(p.trades.some(x=>x.crypto&&x.delta>0));assert(p.cashAfter>=0);const n=w.Portfolio.execute(s,p,p.trades.filter(x=>x.delta).map(x=>({id:x.id,quantity:x.delta,price:x.price,fee:0})));assert.equal(w.Portfolio.calc(n).total,w.Portfolio.calc(s).total);assert.equal(n.cashflows.length,0)});
t('fixed amount unchanged, dynamic weight, infeasible warning',()=>{let s=fresh({stocks:[stock('A',0,100)],cash:{amount:1000},savings:[{id:'s',name:'적금',type:'적금',amount:3000,balance:3000,current:1,total:1,risk:'risk_4'}],riskTargets:{risk_1:0,risk_2:80,risk_3:0,risk_4:20},allocations:{A:80,s:0,cash:20}});assert.equal(s.savings[0].liquidityType,'fixed');const p=w.Portfolio.plan(s);assert(p.warnings.some(x=>x.includes('최소 가능 비중')));assert(p.trades.every(x=>x.id!=='s'));const old=3000/w.Portfolio.calc(s).total;s.cash.amount+=1000;assert.notEqual(3000/w.Portfolio.calc(s).total,old)});
t('locked stock quantity remains after planning',()=>{const s=fresh({stocks:[stock('QQQ',5,100),stock('AAPL',0,100)],cash:{amount:500},riskTargets:{risk_1:0,risk_2:100,risk_3:0,risk_4:0},allocations:{QQQ:0,AAPL:100,cash:0}});const p=w.Portfolio.plan(s,{lockedIds:['QQQ']});assert.equal(p.trades.find(t=>t.id==='QQQ').delta,0)});
t('action plan details collapsed by default',()=>{let s=fresh({stocks:[stock('A',0,100)],cash:{amount:200},riskTargets:{risk_1:0,risk_2:100,risk_3:0,risk_4:0},allocations:{A:100,cash:0}});const x=setup(s,KEY),v=x.w;v.document.querySelector('#full-tab').click();v.document.querySelector('#calculate-plan').click();const details=v.document.querySelector('#plan-output details');assert(details&&!details.open);assert(v.document.querySelector('#plan-output').textContent.includes('예상 잔여 현금'));x.close()});
t('salary invalid destination does not change saved state',()=>{let s=fresh();s.config.salary={amount:4500000,day:1,autoApply:true,targetId:'missing'};const result=w.Cashflow.apply(s);assert.equal(result.changes.length,0);assert.equal(result.pending.length,1);assert.equal(result.state.cash.amount,0)});
console.log(pass+' v0.8 tests PASS');b.close();
